# Build target
script:
 - mc cron ./auto-rebase.sh $TRAVIS_BUILD_NUMBER $GITHUB_SSH_KEY_BASE64

# Install all required dependencies
install:
 - npm install -g mini-cross
 - mc cron echo 'Install successful'

language: node_js

services:
- docker

